In [8]:
import numpy as np
np.array([1,2,3])
a=np.array([1,2,3])
dizi=np.array([1,2,3,3.14])
dizi
dizi=np.array([1,2,3,3,14],dtype=int)
dizi

array([ 1,  2,  3,  3, 14])

1) 1,2,3,4,5 Liste

In [13]:
result=np.array([1,2,3,4,5])
result

array([1, 2, 3, 4, 5])

2) 1,15 arası otomatik oluşturma

In [15]:
result=np.arange(1,16)
result

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

3)50-100 arası 5 er 5 er artacak dizi

In [14]:
result=np.arange(50,101,5)
result

array([ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95, 100])

In [17]:
import numpy as np

py_list = [1,2,3,4,5,6,7,8,9]

np_array = np.array([1,2,3,4,5,6,7,8,9]) # assign the array to np_array

print(type(py_list))
print(type(np_array))

py_multi = [[1,2,3],[4,5,6],[7,8,9]]
np_multi = np.array(py_multi)

<class 'list'>
<class 'numpy.ndarray'>


In [18]:
print(py_list)
print(np_multi)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
print(np_array.ndim)
print(np_multi.ndim)

1
2


In [20]:
print(np_array.shape)
print(np_multi.shape)

(9,)
(3, 3)
